"use client";

import { useMemo, useState } from "react";
import { useAccount, useWriteContract } from "wagmi";
import { FEE_ROUTER_CONTRACT_ADDRESS } from "@/lib/constants";
import type { Creator } from "@/lib/mock-data";
import { CheckCircleIcon } from "@/components/ui/Icons";

// This is the client-side half of the real claim flow: it connects a real
// EVM wallet (via wagmi) and, once the FeeRouter contract from
// /contracts is deployed to Robinhood Chain and its address is set in
// NEXT_PUBLIC_FEE_ROUTER_CONTRACT_ADDRESS, calls its `claim(string handle)`
// function. Until that env var is set, the button explains why claiming is
// disabled instead of silently pretending to move funds — see
// contracts/README.md to deploy it.

const PLACEHOLDER_CONTRACT_ADDRESS = "0x488180620deeb35bf3f2c7e46d0b03d314a4a057";

// Minimal hand-written ABI covering just the function this panel calls —
// the full ABI (generated by `solc`/Hardhat) lives alongside the compiled
// contract in /contracts once you build it there.
const FEE_ROUTER_ABI = [
  {
    type: "function",
    name: "claim",
    stateMutability: "nonpayable",
    inputs: [{ name: "handle", type: "string" }],
    outputs: [],
  },
] as const;

export default function ClaimPanel({ creator }: { creator: Creator }) {
  const { address, isConnected } = useAccount();
  const { writeContractAsync } = useWriteContract();
  const [status, setStatus] = useState<"idle" | "sending" | "sent" | "error">("idle");
  const [errorMsg, setErrorMsg] = useState<string | null>(null);
  const [txHash, setTxHash] = useState<string | null>(null);

  const contractDeployed = useMemo(
    () => FEE_ROUTER_CONTRACT_ADDRESS.toLowerCase() !== PLACEHOLDER_CONTRACT_ADDRESS,
    []
  );

  async function handleClaim() {
    if (!address) return;
    setStatus("sending");
    setErrorMsg(null);
    try {
      const hash = await writeContractAsync({
        address: FEE_ROUTER_CONTRACT_ADDRESS,
        abi: FEE_ROUTER_ABI,
        functionName: "claim",
        args: [creator.handle],
      });
      setTxHash(hash);
      setStatus("sent");
    } catch (err) {
      setErrorMsg(err instanceof Error ? err.message : "Claim failed.");
      setStatus("error");
    }
  }

  return (
    <div className="card overflow-hidden">
      <div className="grid grid-cols-3 divide-x divide-white/8 border-b border-white/8">
        <StatTile label="Earned" value={creator.earnedEth} />
        <StatTile label="Available" value={creator.availableEth} tone="#FFB84A" />
        <StatTile label="Sent" value={creator.sentEth} tone="#2DD4BF" />
      </div>

      <div className="p-6">
        {!isConnected ? (
          <p className="text-center text-sm leading-relaxed text-white/50">
            Connect the wallet that verified this creator to claim.
          </p>
        ) : !contractDeployed ? (
          <div className="rounded-lg border border-white/10 bg-white/[0.03] px-4 py-3.5 text-xs leading-relaxed text-white/50">
            The FeeRouter contract hasn&apos;t been deployed yet, so claiming
            is disabled in this preview. Deploy{" "}
            <code className="rounded bg-white/5 px-1 py-0.5 text-white/70">contracts/</code>{" "}
            to Robinhood Chain and set{" "}
            <code className="rounded bg-white/5 px-1 py-0.5 text-white/70">
              NEXT_PUBLIC_FEE_ROUTER_CONTRACT_ADDRESS
            </code>{" "}
            to enable it — see contracts/README.md.
          </div>
        ) : (
          <button
            onClick={handleClaim}
            disabled={status === "sending" || creator.availableEth <= 0}
            className="btn btn-primary w-full"
          >
            {status === "sending"
              ? "Confirming…"
              : `Claim ${creator.availableEth} ETH`}
          </button>
        )}

        {status === "sent" && txHash && (
          <p className="mt-3 flex items-center justify-center gap-1.5 text-center text-xs text-[#2DD4BF]">
            <CheckCircleIcon className="h-3.5 w-3.5" />
            Sent. Tx: {txHash.slice(0, 10)}…
          </p>
        )}
        {status === "error" && errorMsg && (
          <p className="mt-3 text-center text-xs text-red-400">{errorMsg}</p>
        )}
      </div>
    </div>
  );
}

function StatTile({
  label,
  value,
  tone,
}: {
  label: string;
  value: number;
  tone?: string;
}) {
  return (
    <div className="px-4 py-5 text-center">
      <div className="text-xs text-white/45">{label}</div>
      <div
        className="mt-1.5 font-mono text-lg font-semibold tabular-nums"
        style={{ color: tone ?? "var(--foreground)" }}
      >
        {value.toLocaleString()}
      </div>
    </div>
  );
}
